// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ppu.Data;

#nullable disable

namespace Ppu.Migrations
{
    [DbContext(typeof(PpuDbContext))]
    [Migration("20260501063431_InitRawReadHistory")]
    partial class InitRawReadHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Ppu.Data.Entities.RawReadHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RegisterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistersJson")
                        .IsRequired()
                        .HasMaxLength(270)
                        .HasColumnType("TEXT");

                    b.Property<ushort>("StartAddress")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppRunId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("RawReadHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
